name: renderer
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=0.15.0=pyhd3eb1b0_0
  - aiohttp=3.8.1=py310h7f8727e_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anyio=3.5.0=py310h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py310h06a4308_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.6.15=py310h06a4308_0
  - cffi=1.15.1=py310h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - flatbuffers=2.0.0=h2531618_0
  - fonttools=4.34.4=py310h5764c6d_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.2.0=py310h7f8727e_1
  - gast=0.5.3=pyhd3eb1b0_0
  - giflib=5.2.1=h36c2ea0_2
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.46.1=h33aed49_0
  - grpcio=1.42.0=py310hce63b2e_0
  - h5py=3.7.0=py310he06866b_0
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py310h06a4308_0
  - ipykernel=6.9.1=py310h06a4308_0
  - ipython=8.4.0=py310h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9e=h166bdaf_2
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.4.0=py310h06a4308_0
  - jupyter_client=7.2.2=py310h06a4308_0
  - jupyter_core=4.10.0=py310h06a4308_0
  - jupyter_server=1.18.1=py310h06a4308_0
  - jupyterlab=3.4.4=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.12.0=py310h06a4308_0
  - keras=2.8.0=py310h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py310hbf28c38_0
  - krb5=1.19.2=hac12032_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcurl=7.84.0=h91b91d3_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=12.1.0=h8d9b700_16
  - libnghttp2=1.46.0=hce63b2e_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=hf726d26_0
  - libpng=1.6.37=h753d276_3
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h0e0dad5_3
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.3=h522a892_1
  - libwebp-base=1.2.3=h166bdaf_2
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.12=h166bdaf_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.3.4=py310h06a4308_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-base=3.5.2=py310h5701ce4_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py310h7f8727e_1000
  - mplfinance=0.12.9b1=pyhd8ed1ab_0
  - multidict=5.1.0=py310h7f8727e_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py310h06a4308_0
  - nbconvert=6.4.4=py310h06a4308_0
  - nbformat=5.3.0=py310h06a4308_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=py310h06a4308_0
  - notebook=6.4.12=py310h06a4308_0
  - numpy=1.22.3=py310h4f1e569_0
  - numpy-base=1.22.3=py310hf2716ce_0
  - oauthlib=3.2.0=pyhd3eb1b0_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.3=py310h769672d_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py310he619898_0
  - pip=22.2.2=pyhd8ed1ab_0
  - prometheus_client=0.14.1=py310h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.20.1=py310h295c915_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.4.0=py310h06a4308_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.0=py310h7f8727e_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2022.1=pyhd8ed1ab_0
  - pyzmq=23.2.0=py310h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=py310h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.7.3=py310h4f1e569_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=63.4.2=py310hff52083_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py310h06a4308_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.39.2=h4ff8645_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.8.0=py310h06a4308_0
  - tensorboard-data-server=0.6.0=py310hca6d32c_0
  - tensorboard-plugin-wit=1.8.1=py310h06a4308_0
  - tensorflow=2.8.2=mkl_py310hd2b8f8c_0
  - tensorflow-base=2.8.2=mkl_py310hf890080_0
  - tensorflow-estimator=2.8.0=py310h2f386ee_0
  - termcolor=1.1.0=py310h06a4308_1
  - terminado=0.13.1=py310h06a4308_0
  - testpath=0.6.0=py310h06a4308_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.1=py310h7f8727e_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=py310h06a4308_0
  - typing_extensions=4.3.0=py310h06a4308_0
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - urllib3=1.26.11=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=0.58.0=py310h06a4308_4
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py310h7f8727e_1
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py310h06a4308_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h8a70e8d_3
  - pip:
    - pyyaml==6.0
prefix: /home/apache/miniconda3/envs/renderer
